extends: eslint-config-standard-prettier-fp

plugins: [eslint-plugin-ava]

rules:
  # AVA
  ava/no-unknown-modifiers: 2
  ava/use-t-well: 2
  ava/no-todo-implementation: 2
  ava/no-nested-tests: 2
  ava/no-duplicate-modifiers: 2
  ava/assertion-arguments: 2
  ava/no-cb-test: 2
  ava/test-ended: 2
  ava/no-invalid-end: 2
  ava/no-statement-after-end: 2
  ava/test-title: 2
  ava/no-identical-title: 2
  ava/no-ignored-test-files: 2
  ava/no-import-test-files: 2
  ava/no-only-test: 2
  ava/no-skip-test: 2
  ava/no-skip-assert: 2
  ava/no-todo-test: 2
  ava/use-true-false: 2
  ava/max-asserts: [2, 5]
  ava/use-t: 2
  ava/use-test: 2
  ava/prefer-async-await: 2
  ava/no-async-fn-without-await: 2

# We do not use Power assert directly
# ava/prefer-power-assert: 2
